Repository python/python-docs-fr, pull requests merged in 2019-11, with the labels that each got.

#960 Traduction de glossary.po
  glossary.po
Labels: awaiting changes

#945 Traduction de pathlib
  library/pathlib.po
Labels: need review

#977 Fixed fuzzies in reference/
  reference/datamodel.po
  reference/expressions.po
Labels: need review

#914 correction d'une fuzzy dans library/debug.op
  library/debug.po
Labels: awaiting changes

#978 use padpo, translate fuzzy and empty translation
  library/pathlib.po
Labels: need review

#984 powrap and pospell on changed files only
  .travis.yml
Labels: need review

#619 Traduction des premières lignes de asyncio-policy.po
  library/asyncio-policy.po
Labels: awaiting changes, on hold

#1010 Fixed fuzzies in library/stringprep.po
  library/stringprep.po
Labels: need review

#1003 Fuzzies in library/urllib.robotparser.po
  library/urllib.robotparser.po
Labels: need review

#1001 Fuzzies in library/xml.sax.po
  library/xml.sax.po
Labels: need review

#1000 Fuzzies in library/zipimport.po
  library/zipimport.po
Labels: need review

#999 Fuzzies in library/datatypes.po
  library/datatypes.po
Labels: need review

#996 Fixed fuzzies in reference/import.po
  reference/import.po
Labels: need review

#936 Howto
  faq/design.po
  howto/pyporting.po
  howto/regex.po
  howto/sorting.po
Labels: awaiting changes, need review

#899 Finished translating using/cmdline.po
  dict
  using/cmdline.po
Labels: need review

#956 Ajout de traduction manquante + modification d'un Fuzzy dans library/json.po
  library/json.po
Labels: awaiting changes
