Repository python/python-docs-fr, pull requests merged in 2020-12, with the labels that each got.

#1493 Problem Matcher for pospell
  .github/problem-matchers/pospell.json
  .github/workflows/tests.yml
  .travis.yml
Labels: 🤖 automerge

#1463 Traduction de faq/library.po
  faq/library.po
Labels: 🤖 automerge

#1461 Traduction de faq/general.po
  faq/general.po
Labels: 🤖 automerge

#1482 CONTRIBUTING-CORE.rst
  CONTRIBUTING-CORE.rst
  CONTRIBUTING.rst
Labels: 🤖 automerge

#1485 Ajout de « roughly » au dictionnaire.
  CONTRIBUTING.rst
Labels: 🤖 automerge

#1495 L'accent.
  library/sys.po
Labels: 🤖 automerge

#1497 Update tests.yml for all french names
  .github/workflows/pr-title-cheker.yml
  .github/workflows/tests.yml
Labels: meta, 🤖 automerge

#1496 Updated poutils to 0.10.0
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-cheker.yml
  requirements.txt
Labels: meta, 🤖 automerge

#1498 Relecture de library/time.po
  library/time.po
Labels: 🤖 automerge

#1478 library/marshal
  library/marshal.po
Labels: 🤖 automerge

#1501 Set a shorter timeout on this build (6h by default).
  .github/workflows/tests.yml
Labels: 🤖 automerge

#1500 Github checks only changed files
  .github/workflows/tests.yml
  library/aifc.po
  library/allos.po
  library/zoneinfo.po
Labels: 🤖 automerge

#1423 Library.logging.handlers.po
  library/logging.handlers.po
  requirements.txt
Labels: 🤖 automerge

#1503 Relecture library/functions
  library/functions.po
Labels: 🤖 automerge

#1506 Fix: Typo reported by WW60 on IRC.
  library/string.po
Labels: 🤖 automerge

#1507 Fuzzy in using/windows.po
  using/windows.po
Labels: 🤖 automerge

#1508 tutorial/inputoutput.po
  tutorial/inputoutput.po
Labels: 🤖 automerge

#1509 Modifications mineures du guide de contribution.
  CONTRIBUTING.rst
Labels: meta
