Repository python/python-docs-fr, pull requests merged in 2021-04, with the labels that each got.

#1588 fuzzies dans library/tarfile.po
  library/tarfile.po
Labels: 🤖 automerge

#1590 Traduction des fuzzies de Reference et Tutorial
  reference/compound_stmts.po
  reference/datamodel.po
  reference/executionmodel.po
  reference/expressions.po
  reference/grammar.po
  reference/import.po
  reference/lexical_analysis.po
  reference/simple_stmts.po
  tutorial/controlflow.po
Labels: 🤖 automerge

#1593 Traduction de la fuzzy de ipaddress.po
  library/ipaddress.po
Labels: 🤖 automerge

#1597 Added locales folder to potodoignore, which could cause confusion
  .potodoignore
Labels: meta, 🤖 automerge

#1603 Few lines (but it's deprecated) on install/index.po
  install/index.po
Labels: 🤖 automerge

#1599 Fuzzy in library/zlib.po
  library/zlib.po
Labels: 🤖 automerge

#1604 Translating howto/cporting.po
  howto/cporting.po
Labels: 🤖 automerge

#1601 Fuzzy in library/xml.po
  library/xml.po
Labels: 🤖 automerge

#1613 ligne 19 howto/urllib2.po
  howto/urllib2.po
Labels: 🤖 automerge

#1600 Fuzzy & untranslated dans library/zipfile.po
  library/zipfile.po
Labels: 🤖 automerge

#1602 Fuzzy in library/unittest.po
  library/unittest.po
Labels: 🤖 automerge

#1608 Traduction de library/2to3.po
  library/2to3.po
Labels: 🤖 automerge

#1611 Makefile: don't run sphinx in quiet mode
  Makefile
Labels: meta
