Repository python/python-docs-fr, pull requests merged in 2021-02, with the labels that each got.

#1533 fix alphabetical order in glossary
  CONTRIBUTING.rst
Labels: 🤖 automerge

#1535 complète Open après rajout d'une phrase en anglais
  library/functions.po
Labels: 🤖 automerge

#1521 Fuzzies in howto
  howto/instrumentation.po
  howto/logging.po
  howto/pyporting.po
  howto/sorting.po
Labels: EASY, 🤖 automerge

#1541 FIX: Typo.
  library/re.po
Labels: 🤖 automerge

#1542 (Encore) quelques modifications du README.
  README.rst
Labels: meta, 🤖 automerge

#1539 library/functools : fuzzys et traductions de cache/lru_cache.
  library/functools.po
Labels: 🤖 automerge

#1439 Traduction de extending/extending.po 10011628
  extending/extending.po
  extending/newtypes.po
Labels: 🤖 automerge

#1536 Traduction de library/zoneinfo.po
  library/zoneinfo.po
Labels: 🤖 automerge
