Repository python/python-docs-fr, pull requests merged in 2021-05, with the labels that each got.

#1616 Tradution de library/compileall.po
  library/compileall.po
Labels: 🤖 automerge

#1618 Traduction de py_compile.po
  library/py_compile.po
Labels: 🤖 automerge

#1624 Traduction de c-api/bytearray.po
  c-api/bytearray.po
Labels: 🤖 automerge

#1598 Fuzzy & untranslated de using/windows.po
  using/windows.po
Labels: 🤖 automerge

#1619 Makefile: don't run `git checkout -` at the end of the build
  Makefile
Labels: meta

#1635 Forward port from 3.6.
  faq/programming.po
  library/argparse.po
  library/locale.po
  library/lzma.po
  whatsnew/3.10.po
  whatsnew/3.9.po
  whatsnew/changelog.po
Labels: meta

#1649 Fuzzy de library/gettext.po
  library/gettext.po
Labels: 🤖 automerge

#1642 Ajout d'une section sur la gestion des suggestions
  CONTRIBUTING.rst
Labels: meta

#1629 Correction contresens et typographie dans library/heapq.po
  library/heapq.po
Labels: 🤖 automerge

#1645 Fuzzy de library/contextlib.po
  library/contextlib.po
Labels: 🤖 automerge

#1647 Fuzzy de library/asyncio.po.
  library/asyncio.po
Labels: 🤖 automerge

#1639 Make merge
  c-api/contextvars.po
  faq/programming.po
  faq/windows.po
  howto/descriptor.po
  library/argparse.po
  library/array.po
  library/asyncio-protocol.po
  library/asyncio-subprocess.po
  library/asyncio-task.po
  library/audit_events.po
  library/cgi.po
  library/codecs.po
  library/compileall.po
  library/configparser.po
  library/dataclasses.po
  library/email.compat32-message.po
  library/email.po
  library/exceptions.po
  library/ftplib.po
  library/functions.po
  library/http.server.po
  library/idle.po
  library/importlib.metadata.po
  library/importlib.po
  library/io.po
  library/ipaddress.po
  library/numbers.po
  library/operator.po
  library/os.path.po
  library/os.po
  library/pathlib.po
  library/py_compile.po
  library/resource.po
  library/socket.po
  library/sqlite3.po
  library/ssl.po
  library/stdtypes.po
  library/string.po
  library/subprocess.po
  library/sys.po
  library/threading.po
  library/types.po
  library/typing.po
  library/unittest.po
  library/urllib.parse.po
  library/zipfile.po
  reference/compound_stmts.po
  reference/datamodel.po
  reference/expressions.po
  reference/simple_stmts.po
  tutorial/controlflow.po
  tutorial/datastructures.po
  tutorial/errors.po
  tutorial/inputoutput.po
  tutorial/venv.po
  using/windows.po
  whatsnew/3.9.po
  whatsnew/changelog.po
Labels: meta, 🤖 automerge

#1626 Traduction de library/configparser.po
  library/configparser.po
Labels: 🤖 automerge

#1643 Traduction de library/platform.po
  TRANSLATORS
  library/platform.po
Labels: 🤖 automerge

#1641 traduction de library/contextvars.po
  TRANSLATORS
  library/contextvars.po
Labels: 🤖 automerge

#1621 Traduction partielle de howto/clinic.po
  howto/clinic.po
Labels: 🤖 automerge
