Repository python/python-docs-fr, pull requests merged in 2021-09, with the labels that each got.

#1682 Amélioration de CONTRIBUTING.rst sur Poutils
  CONTRIBUTING.rst
Labels: meta

#1678 Fuzzies un peu partout
  faq/design.po
  faq/gui.po
  faq/windows.po
  library/__future__.po
  library/argparse.po
  library/email.encoders.po
  library/email.po
  library/linecache.po
  library/string.po
  library/timeit.po
  license.po
  reference/compound_stmts.po
  reference/datamodel.po
  reference/expressions.po
  reference/simple_stmts.po
  tutorial/controlflow.po
  tutorial/errors.po
  using/windows.po
Labels: meta

#1691 Traduction de library/ast.po
  CONTRIBUTING.rst
  library/ast.po
Labels: 🤖 automerge

#1690 Traduction de library/fileinput.po
  dict
  library/fileinput.po
Labels: 🤖 automerge

#1688 Avoid having this sha1 at two different places.
  .github/workflows/tests.yml
Labels: meta

#1652 Traduction de whatsnew/3.9.po
  whatsnew/3.9.po
Labels: 🤖 automerge

#1702 Fuzzies in tutorial/appetite.po
  tutorial/appetite.po
Labels: 🤖 automerge

#1701 Fuzzies in tutorial/errors.po
  tutorial/errors.po
Labels: 🤖 automerge

#1700 Fuzzies in tutorial/floatingpoint.po
  tutorial/floatingpoint.po
Labels: 🤖 automerge

#1699 Fuzzies in tutorial/index.po
  tutorial/index.po
Labels: 🤖 automerge

#1698 Fuzzies in tutorial/interpreter.po
  tutorial/interpreter.po
Labels: 🤖 automerge

#1697 Fuzzies in tutorial/whatnow.po
  tutorial/whatnow.po
Labels: 🤖 automerge

#1696 Some fuzzy in using/.
  using/cmdline.po
  using/unix.po
  using/windows.po
Labels: meta, 🤖 automerge

#1675 Use our own cpython clone.
  CONTRIBUTING-CORE.rst
  Makefile
Labels: meta

#1605 Work on extending/newtypes_tutorial.po
  extending/newtypes_tutorial.po
Labels: 🤖 automerge
