Repository python/python-docs-fr, pull requests merged in 2021-01, with the labels that each got.

#1499 Trying to simplify the Makefile
  .gitignore
  Makefile
  c-api/arg.po
Labels: 🤖 automerge

#1513 Correction fuzzy
  library/csv.po
Labels: 🤖 automerge

#1514 Contributing out of Github
  CONTRIBUTING.rst
Labels: meta, 🤖 automerge

#1515 Sync github/workflow commit with Makefile commit.
  .github/workflows/tests.yml
Labels: meta, 🤖 automerge

#1522 Mise à jour de la vidéo gource
  README.rst
Labels: meta, 🤖 automerge

#1517 Fixed fuzzies in c-api
  c-api/concrete.po
  c-api/mapping.po
Labels: EASY, 🤖 automerge

#1520 Fuzzies in FAQ
  faq/programming.po
  faq/windows.po
Labels: EASY, 🤖 automerge

#1510 Traduction de quelques fuzzies
  library/datetime.po
Labels: 🤖 automerge
