Repository python/python-docs-fr, pull requests merged in 2021-03, with the labels that each got.

#1547 Make merge before atelier
  c-api/conversion.po
  c-api/unicode.po
  extending/newtypes.po
  howto/descriptor.po
  howto/urllib2.po
  install/index.po
  library/cgi.po
  library/dis.po
  library/functions.po
  library/idle.po
  library/shutil.po
  library/sqlite3.po
  library/sys.po
  library/turtle.po
  library/unittest.po
  library/urllib.parse.po
  library/venv.po
  reference/expressions.po
  tutorial/controlflow.po
  using/windows.po
  whatsnew/3.6.po
  whatsnew/3.7.po
  whatsnew/3.8.po
  whatsnew/3.9.po
  whatsnew/changelog.po
Labels: meta, 🤖 automerge

#1549 Update sorting.po
  howto/sorting.po
Labels: 🤖 automerge

#1540 Traduction des nouveaux messages dans library/argparse.po
  library/argparse.po
Labels: 🤖 automerge

#1543 Added .venv to gitignore and updated poutils in requirements.txt
  .gitignore
  requirements.txt
Labels: meta, 🤖 automerge

#1518 Fixed fuzzies in distutils
  distutils/apiref.po
  distutils/builtdist.po
  distutils/index.po
Labels: EASY, 🤖 automerge

#1519 More fuzzies in copyright and glossary
  copyright.po
  glossary.po
Labels: EASY, 🤖 automerge

#1530 Traduction de library/turtle.po à 100%
  library/turtle.po
Labels: 🤖 automerge

#1553 Fix: Compatibility with Sphinx>=3.3.1.
  glossary.po
Labels: meta, 🤖 automerge

#1555 Make merge
  Makefile
  c-api/decimal.po
  c-api/file.po
  c-api/init.po
  c-api/memory.po
  c-api/sys.po
  c-api/unicode.po
  faq/design.po
  howto/descriptor.po
  library/ast.po
  library/collections.po
  library/concurrency.po
  library/ctypes.po
  library/dataclasses.po
  library/ensurepip.po
  library/enum.po
  library/ftplib.po
  library/functions.po
  library/gc.po
  library/imaplib.po
  library/io.po
  library/json.po
  library/logging.po
  library/mmap.po
  library/nntplib.po
  library/os.po
  library/pdb.po
  library/poplib.po
  library/pty.po
  library/resource.po
  library/shutil.po
  library/signal.po
  library/smtplib.po
  library/socket.po
  library/sqlite3.po
  library/subprocess.po
  library/sys.po
  library/syslog.po
  library/telnetlib.po
  library/tempfile.po
  library/threading.po
  library/time.po
  library/types.po
  library/typing.po
  library/unittest.mock.po
  library/unittest.po
  library/urllib.request.po
  library/winreg.po
  reference/datamodel.po
  reference/simple_stmts.po
  using/cmdline.po
  whatsnew/3.10.po
  whatsnew/3.9.po
Labels: meta, 🤖 automerge

#1559 Traduction de library/timeit.po
  library/timeit.po
Labels: 🤖 automerge

#1554 Traduction de library/zoneinfo.po
  library/zoneinfo.po
Labels: 🤖 automerge

#1561 Traduction de library/collections.po
  library/collections.po
Labels: 🤖 automerge

#1575 FIX: Checkout before telling the user to install Sphinx.
  Makefile
Labels: meta
