Repository python/python-docs-fr, pull requests merged in 2022-05, with the labels that each got.

#1869 howto: fuzzies
  howto/annotations.po
  howto/functional.po
  howto/ipaddress.po
  howto/regex.po
  howto/sorting.po
Labels: meta

#1798 Relecture complète et complément de library/csv.po
  dict
  library/csv.po
Labels: 🤖 automerge

#1886 using/windows.po
  using/windows.po
Labels: 🤖 automerge

#1531 Started translating library/os.po
  library/os.po
Labels: DO NOT MERGE
